# Generated by Django 4.1.3 on 2022-12-06 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_usuaruios', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(db_column='Nombres', max_length=50)),
                ('apellidos', models.CharField(db_column='Apellidos', max_length=50)),
                ('mail', models.CharField(db_column='Mail', max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id_notas', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField()),
                ('id_usuarios', models.ForeignKey(db_column='id_usuarios', on_delete=django.db.models.deletion.DO_NOTHING, to='Block_Notas.login')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'notas',
            },
        ),
    ]
