# Generated by Django 4.1.3 on 2022-12-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Block_Notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_usuaruios',
            new_name='id_usuarios',
        ),
    ]
