# Generated by Django 4.1.3 on 2022-12-14 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Block_Notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='id_usuarios',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
